name: page update

on:
  schedule:
    - cron: '0 17 * * 1-5'
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set-up python
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Run HTML generator
      run: |
        python generate_html.py
      env:
        BROKER_LOGIN: ${{ secrets.BROKER_LOGIN }}
        BROKER_PASSWORD: ${{ secrets.BROKER_PASSWORD }}

    - name: Commit and Push
      uses: offensive-vk/auto-commit-push@v5
      with:
        name: 'GitHub Action'
        email: 'actions@github.co'
        message: 'auto-update of html page'
        branch: main
        github-token: ${{ secrets.TOKEN }}
